(in-package :cl-user)

(defpackage :common-symbols 
  (:import-from :system-tool "FILE-PROPERTY-LIST")
  (:export "INTERACTOR" "*INTERACTOR*"
	   "VIEW" "TOP-VIEW" "WINDOW"
	   "WINDOW-FRAME" "TILED-WINDOW-FRAME"
	   "VIEW-DISPLAY-ATTRIBUTES"

	   "COPY"

	   "FEET" "METERS"

	  ;; "FREEDIUS-PREFIX"

	   "2D-WORLD" "3D-WORLD" "WORLD"  "3D-TO-2D-PROJECTION"
	   
	   "2D-TO-WINDOW-MATRIX" "2D-TO-WINDOW-TRANSFORM" "IMAGE-TO-2D-TRANSFORM"
	   "OBJECT-SET"
	   "OBJECT-TO-WORLD-TRANSFORM" "OBJECT-TO-WORLD-MATRIX"
	   "OBJECT-TO-PARENT-TRANSFORM" "OBJECT-TO-PARENT-MATRIX"
	   "IMMEDIATE-RENDER-P" "SELECTED-OBJECTS" "GL-IS-DIRECT-P"
	   "TRANSFORM-MATRIX"
	   ;;"SUPERIOR-COORDINATE-SYSTEM"
	   "PARENT" "CHILDREN"
	   "LVCS-TO-GEOCENTRIC-TRANSFORM"
	   "BASIC-COORDINATE-SYSTEM"
	   "DIMENSIONALITY"
	   
	   "NAME"
	   ;; should these be here
	   
	   "FV" ; this should be removed ?
	   "INFERIORS"
	   "FILE-PROPERTY-LIST"

	   "ORIGIN" "SET-ORIGIN"

	   "<1>" "<ALPHA-1>" "<BETA-1>" "<ALPHA-BETA-1>" "<GAMMA-1>"
	   "<ALPHA-GAMMA-1>" "<BETA-GAMMA-1>" "<ALPHA-BETA-GAMMA-1>"
	   
	   "<2>" "<ALPHA-2>" "<BETA-2>" "<ALPHA-BETA-2>" "<GAMMA-2>"
	   "<ALPHA-GAMMA-2>" "<BETA-GAMMA-2>" "<ALPHA-BETA-GAMMA-2>"
	   
	   "<3>" "<ALPHA-3>" "<BETA-3>" "<ALPHA-BETA-3>" "<GAMMA-3>"
	   "<ALPHA-GAMMA-3>" "<BETA-GAMMA-3>" "<ALPHA-BETA-GAMMA-3>"

	   "IO-ATTRIBUTES"

	   ))
