(in-package :cl-user)

;;; lisp-extensions package is already defined by bootstrap
;;; Perhaps lisp-extensions shouldn't be defined in bootstrap,
;;; but common-symbols package instead.

(defpackage :lisp-extensions (:nicknames :lx)
  (:use :common-lisp :common-symbols :lcl 
	;:ev-pathnames
	) 
  (:import-from :ev-pathnames EV-PATHNAME-TRANSLATE EV-PATHNAME-REGISTER)
  #+allegro(:import-from :excl "PATHNAME-AS-DIRECTORY" "DEFADVICE")
  #+cmu    (:import-from :ext truly-the RUN-PROGRAM QUIT)
  #+cmu    (:import-from :system WITHOUT-INTERRUPTS)
  #+sbcl    (:import-from :sb-ext truly-the RUN-PROGRAM QUIT)
  #+sbcl    (:import-from :sb-sys WITHOUT-INTERRUPTS)
  #+allegro (:import-from :lcl RUN-PROGRAM)
  #+cmu (:import-from :pcl "UNDEFMETHOD")
  ;;(:import-from :qffi "*PROHIBIT-TYPE-T-FOREIGN-VECTORS*")
  (:import-from :system-tool "CD" "PWD" "ALLOW-REDEFINITION" "IGNORE" "WITHOUT-PACKAGE-LOCKS" 
		"UNWIND-PROTECT-CASE" "GETENV" "MERGE-FREEDIUS-PATH" 
		"*FREEDIUS-EXEC-PREFIX*" "*FREEDIUS-HOME-PATH*" 
		"EV-PATHNAME-TRANSLATE" "EV-PATHNAME-BACKTRANSLATE" "EV-PATHNAME-P" 
		"EV-TO-LOGICAL-PATHNAME"
		)
  (:import-from :system-tool maybe-compile-file-load)
  (:export "CD" "PWD" "ALLOW-REDEFINITION" "IGNORE" "WITHOUT-PACKAGE-LOCKS" 
		     "UNWIND-PROTECT-CASE" #-asdf "GETENV" "MERGE-FREEDIUS-PATH")
	    #+allegro (:import-from :excl "WITHOUT-PACKAGE-LOCKS")

  (:export "MV-BIND" "MV-SETQ" "MV-LIST" "TYPE-EQUIV" "DFLOAT-ANGLE"
	   "CAST"
	   "*DEG-TO-RAD*" "SIND" "COSD" "TAND" "DEGREES" "RADIANS" "DVECTOR"
	   "DSQRT" "TRULY-THE" "SAFE-SORT"
	   "REMASS" "DELASS" "PUTASSOC"
	   "LOAD-TIME-VALUE*"
	   "PROPERTY-LIST-MIXIN" "GET-PROP" "PUT-PROP" "REM-PROP" "PROPERTY-LIST"
	   "WITH-OBJECT-PROPERTIES"
	   "INTERNAL-PROPERTY-LIST-MIXIN" "INTERNAL-GET-PROP" "INTERNAL-PUT-PROP"
	   "INTERNAL-REM-PROP"
	   ;;"ADD-INITIALIZATION" "DO-INITIALIZATIONS"
	   "CME-ARCH-RELATIVE-PATH" "CME-RELATIVE-PATH" "DIR-RELATIVE-PATH"
	   "MERGE-DIRECTORIES-AND-PATHNAME"
	   "ALLOW-REDEFINITION"
	   "REMOVEF"
	   "USER-EMAIL-ADDRESS" "USERNAME"
	   "UNWIND-PROTECT-CASE"
	   "NEQ" "WITH-SLOT-VALUES" "FASD-FORM-PROPERTY-LIST-MIXIN" "FASD-FORM-MIXIN"
	   "FASD-FORM" "FASD-FORM-P" "FASD-FORM-INIT-PLIST" "FASD-FORM-PROPERTIES-LIST-DO-NOT-DUMP"
	   "DEFINE-FASD-FORM-INIT-PLIST"
	   "STRING-SEARCH-SET" "STRING-SEARCH-NOT-SET" "SUBSTRING"
	   "PARSE-PRINTED-UNIVERSAL-TIME" "PRINT-UNIVERSAL-DATE"
	   "PRINT-UNIVERSAL-TIME"
	   "ABBREV-PRINT-UNIVERSAL-DATE" "PARSE-ABBREV-TIMESTRING"
	   "PARSE-ABBREV-TIMESTRING2"
	   "PRINT-LISP-PROMPT"
	   "DEFUN-CACHED" "DEFMETHOD-CACHED"
	   "EVAL-CACHE-FLUSH-FUNCTION" "EVAL-CACHE-FLUSH" "EVAL-CACHE" "DEF-EVAL-CACHE-SEARCH-RULE"
	   "^2" "^2-P" "LOG2" "PAD-TO-MULTIPLE" "TRUNCATE-TO-MULTIPLE"
	   "TRUNCATE!" "ROUND!"
	   "RANDOM-IN-RANGE" "NORMAL-RANDOM"
;;;	   "MAKE-FOREIGN-VECTOR" "UNMAKE-FOREIGN-VECTOR" "MAKE-FOREIGN-ARRAY"
;;;	   "STATIONARY-ARRAY-CHECK" "MAKE-STATIONARY-VECTOR" "UNMAKE-STATIONARY-VECTOR"
	   
	   "GET-CLASS-PROTOTYPE"
	   "DEFFLAVOR-CLASS"
	   "DEFSTRUCT-CLASS" "DEFSTRUCT-CLASS-P"
	   "WITH-CLASS-SLOTS" "WITH-CLASS-SLOT-VALUES" "CLASS-SLOT-VALUE"
	   "BASE-STRUCT-CLASS" "FASD-FORM-INIT-PLIST-STRUCT" "PROPERTY-LIST-STRUCT"

	   "PATHNAME-AS-DIRECTORY" "PATHNAME-AS-FILE" "PATHNAME-IMMEDIATE-DIRECTORY-NAME"
	   "PATHNAME-DIRECTORY-PATH" "PATH-WITH-VERSION-P"
	   "EV-PATHNAME-P" "EV-PATHNAME-TRANSLATE"
	   "CREATE-DIRECTORY" "PATH-ABSOLUTE-P"
	   "SYMBOLIC-LINK-P" "DIRECTORY-P" "FILE-LENGTH" "GET-SYMBOLIC-LINK"
	   "FOLLOW-SYMBOLIC-LINKS" "UNIX-DOT-DIRECTORY-P"
	   "BACKUP-FILE-PATHNAME" "BACKUP-FILE" "BACKUP-FILE-BY-RENAME"
	   "BACKUP-FILE-BY-COPY"
	   "WITH-DIRECTORY" "MAKE-DIRECTORY-LINK"
	   "COPY-FILES" "RUN-PROGRAM-PATHNAME"
	   ;"FILE-PROPERTY-LIST"
	   "MAKE-INT-VECTOR"
	   "WITH-ELEMENT-TYPES" "COPY-ARRAY" "COPY-ARRAY-CONTENTS" "FAST-FILL-ARRAY" "LISTARRAY"
	   "ADJUST-ARRAY-COPY"
	   "MAYBE-COMPILE-FILE-LOAD"
	   "STRING-PREFIX-EQUAL" "STRING-PREFIX="

	   "CONDITION-CASE"
	   "TO-STRING"
	   #+(or ALLEGRO CMU SBCL) "STRING-APPEND"
	   "MAKE-ARRAY0" "DFLOAT"
	   "DEFINE-SOFT-SLOT" "DEFINE-ACCESSOR-SYNONYM"
	   "SORT-KEYWORD-VALUE-LIST"

	   "UNDEFMETHOD"
	   "GETPID"
	   )
  
  )
