(in-package :cl-user)

(defpackage :math
  (:use :common-lisp :lx :common-symbols)
  (:use :lcl) (:import-from :lcl "WITHOUT-FLOATING-UNDERFLOW-TRAPS")
;;  (:import-from :common-lisp "*PRINT-ARRAY*")
  (:export
   "COPY-ARRAY" "COPY-ARRAY-CONTENTS" "COPY-MATRIX"
   
   "MAKE-AND-FILL-2D-ARRAY"
   "MAKE-AND-FILL-4X4-MATRIX" "MAKE-4X4-MATRIX" "MAKE-4X4-IDENTITY-MATRIX" "SET-4X4-IDENTITY-MATRIX"
   "COPY-4X4-MATRIX" "MULTIPLY-4X4-MATRICES" "CLEAR-4X4-MATRIX" 
   "DMATRIX" "MATRIX" "DVECTOR" "MAKE-DMATRIX" "MAKE-DVECTOR"
   
   "MAKE-ORIENTATION-MATRIX" "MAKE-OBJECT-TO-WORLD-ROTATION-MATRIX"
   "DECOMPOSE-OBJECT-TO-WORLD-ROTATION-MATRIX"
   ;"OMEGA-PHI-KAPPA" "AZIMUTH-TILT-SWING" "HEADING-PITCH-ROLL"
   "MAKE-OBJECT-TO-PARENT-MATRIX"
   
   "MULTIPLY-MATRICES"
   "TRANSPOSE-MATRIX" "TRANSPOSE-4X4-MATRIX" 
   "INVERT-MATRIX" "INVERT-3X3-MATRIX" "INVERT-HOMOGENEOUS-4X4-MATRIX"
   
   "MATRIX-TIMES-VECTOR" "VECTOR-TIMES-MATRIX" "SCALAR-TIMES-MATRIX"
   "3X3-MATRIX-TIMES-VECTOR" "4X4-MATRIX-TIMES-VECTOR" "4X4-PROJECT-VECTOR"

   "SCALE-MATRIX" "SCALE-UPPER-3X3-MATRIX"
	
   "INLINE-CROSS-PROD" "INLINE-INNER-PROD""INLINE-INNER-PROD4"
   "EUCLIDEAN-LENGTH" "INLINE-EUCLIDEAN-LENGTH" "INLINE-MATRIX-TIMES-VECTOR"
   "NORMALIZE-VECTOR-ELEMENTS"
	     
   "LIST-VECTOR" "VECTOR-COPY" "VECTOR-ADD" "VECTOR-DIFFERENCE"
   "VECTOR-LINEAR-COMBINE" "VECTOR-TIMES-SCALAR"
   "VECTOR-CROSS-PRODUCT" "VECTOR-INNER-PRODUCT" "VECTOR-EUCLIDEAN-LENGTH"
   "VECTOR-TO-VECTOR-DISTANCE"
   "NORMALIZE-VECTOR" "NORMALIZE-COORDINATE-VECTOR"
	     
   "SOLVE2R"

   "MAKE-COORDINATE-VECTOR" "CV" "CV3" "COORDINATE-VECTOR" 
   "BIND-VECTOR-ELEMENTS" "COORDINATE-VECTOR-ELEMENTS"
   "COPY-COORDINATE-VECTOR"
   "SET-COORDINATE-VECTOR-ELEMENTS" "MV-SETQ-VECTOR-ELEMENTS"
   
   "ORIGIN" "SET-ORIGIN" "4X4-MATRIX"

   "POINT-INSIDE-POLYGON" "TRIANGLE-NORMAL"
   "3D-POINT-INSIDE-BBOX" "POINT-INSIDE-BBOX"

   "VERTEX-ELEMENT-TYPE" "VERTEX-ARRAY-TYPE" "VERTEX-INDEX-TYPE" "VERTEX-INDEX-ARRAY-TYPE"
   "2D-POINT-IN-BBOX" "POINT-IN-BOUNDING-BOX" "INTERSECT-BOUNDING-BOXES" "UNION-BOUNDING-BOXES" 
   "VERTEX-ARRAY-BOUNDING-BOX"


   "G-" "G*" "G+" "TRANSPOSE" "INVERSE" 
   "RMS-NORM" "MAX-ABS-NORM" "RMS-DIFFERENCE" "MAX-ABS-DIFFERENCE"
   
   ))


;;(load-system-library "libf3dmath")

