#|
This file is automatically generated from the FREEDIUS DEFCUSTOM definitions,
providing a reference definition of all custom variables and their values.
Custom-variable values are set in the following order:

   . Lisp source files
   . $FREEDIUS/lisp/runtime-options.lisp
   . $FREEDIUS_ARCH/lisp/runtime-options.lisp   (optional)
   . $HOME/freedius-init.lisp                   (optional)

Changes to DEFCUSTOM definitions should be made in $FREEDIUS_ARCH/lisp/runtime-options.lisp,
$HOME/freedius-init.lisp, or in the source file where the variable is defined, NOT IN THIS FILE.
Use SLIME meta-dot to access the source code definitions.

This version unhappily assumes that the tk stuff is in $FREEDIUSTK -
ideally we should figure out how to do without that.

|#

(IN-PACKAGE :CUSTOM)


(DEFCUSTOM GUI::*CME-CONTROL-PANEL-LOAD-IMAGE-INITIAL-DIRECTORY*
           "$HOME/"
           (:GROUPS (:GUI))
           "Default directory for Load Image Panel")

(DEFCUSTOM GUI::*ENABLE-TIX-DIR-BROWSER*
           T
           (:GROUPS (:LISPTK))
           "Enable the use of the TIX Directory Tree File Browser from the Control Panel File Menu.")

(DEFCUSTOM GUI::*FREEDIUS-APP-DEFAULTS-FILE*
  (if (member :themed config::*tk-features*)
      nil
      "$FREEDIUSTK/lisp-tk/freedius.app-defaults")
      (:GROUPS (:LISPTK :ESSENTIAL-SETTINGS))
           "Filename for the app-defaults used by most of tk widgets used in FREEDIUS.
To customize for a particular architecture, install a customized version of
$FREEDIUS/lisp-tk/freedius.app-defaults in $FREEDIUS_ARCH/lisp/<xxx>.app-defaults 
and specify a setting for this variable in $FREEDIUS_ARCH/lisp/runtime-options.lisp file.
")

#+never
(DEFCUSTOM GUI::*INSPECTOR-APP-DEFAULTS-FILE*
           (SYSTEM-TOOL::MERGE-SYSTEM-SOURCE-PATHNAME "inspect.app-defaults"
                                                      :INSPECT)
           (:GROUPS (:INSPECT))
           "Filename for the app-defaults used by the INSPECTOR Panel.")

(DEFCUSTOM IMG::*DEFAULT_TMP_FILE_IMAGE_DIR*
           (OR (SYSTEM-TOOL::GETENV "CME_TMP_FILE_IMAGE_DIR")
               "/tmp/CME_TMP_PIX")
           (:TYPE STRING :GROUPS (:IMAGE :ESSENTIAL-SETTINGS))
           "Default directory for creating temporary file images.")
 
(DEFCUSTOM LISP-EXTENSIONS::*FILE-KEPT-OLD-VERSIONS*
           1
           (:GROUPS (:LISP-EXTENSIONS))
           "Number of oldest versions kept by PURGE-DIRECTORY.")

(DEFCUSTOM LISP-EXTENSIONS::*FILE-KEPT-VERSIONS*
           5
           (:GROUPS (:LISP-EXTENSIONS))
           "Number of newest versions kept by PURGE-DIRECTORY.")

(DEFCUSTOM LISPTK::*LISPTK-APP-DEFAULTS-FILE* nil
  ;; Do not bother to load the lisptk  app-defaults file -- freedius-app-defaults now handles everything.   ;; "$FREEDIUS/lisp/tk/lisptk.app-defaults"
  (:GROUPS (:LISPTK))
  "app-defaults filename for \"vanilla\" uses of the :LISPTK subsystem.
To customize for a particular architecture, install a customized version of
$FREEDIUS/lisp-tk/lisptk.app-defaults in $FREEDIUS_ARCH/lisp/<xxx>.app-defaults
and specify a setting for this variable in $FREEDIUS_ARCH/lisp/runtime-options.lisp file.
")

(custom:defcustom LISPTK::*LISPTK-LIBRARY-PATH*  
  (namestring
   (lx::pathname-as-file 
    (truename (if (member :THEMED config::*tk-features*) 
		  "$FREEDIUSTK/tk/library-ttk"
		  "$FREEDIUSTK/tk/library"))))
  (:groups (:lisptk)))

(custom:defcustom *TCL-AUTO-PATH-EXTRAS* "/usr/lib /usr/local/lib"
  ;;(format nil "/usr/lib /usr/local/lib ~a" TK::*LISPTK-LIBRARY-PATH*)
  (:groups (:lisptk))
  "A string containing Tcl auto_path names needed for extra Tk libraries such as Tix and Tile")
